### ISSUE TITLE
Inaccurate notifications

### ISSUE THREAD

**Issue by stemy2** [theAkito/webmon#3]
#### Required Information
Project version
2.0.0
Distro version
Don't know, none of the commands is working.
Kernel version
3.18.140

#### Steps to reproduce

1. Add a website
2. Wait for a notification

#### Expected behaviour

-Notify when something is wrong

#### Actual behaviour

-Notif says "something is wrong" but the app says that everything is good.

**Comment by theAkito** [comment]
Greetings, thank you for telling me about your issue. 🙂

I would like to understand better what's happening.

Did you build the newest version of the app or are you using an older version? I added a lot of features, improvements and fixes since 2.0.0, which is the initial release.

If yes, could you please show me some screenshots of what exactly you mean, when you say, that the app says everything is fine, when the notifications say, something is wrong?

Thank you. 😀

**Comment by stemy2** [comment]
I downloaded it from F-droid.

I have set a specific site and asked the app to warn me every time the site is unreachable.

Fem minutes after doing this, i actually have a notification saying the app can't reach the site. I open the app via the notification, and big surprise: the app says everything is fine. So i have an error notification when everything is working.

I'm sorry, i don't know how to do a screenshot on my phone, so i hope it's clearer.

**Comment by theAkito** [comment]
I see now, no problem.

I just looked at the app's F-Droid page and noticed that there is only the 2.0.0 version of the app available.

I will try to get at least the newest version onto F-Droid.

Still, I will check out your Issue and see if it's perhaps still not working correctly. 🙂

**Comment by theAkito** [comment]
A little check was missing, which was responsible for a failure indication, even if all websites were reachable perfectly fine. Sorry about the trouble. The problem is fixed now. 👍🏻

**Comment by theAkito** [comment]
@stemy2

Version 2.4.0 was just released half an hour ago, on F-Droid. I recommend you to download that version, because notifications are most accurate on that one. 🙂
