### ISSUE TITLE
No autostart

### ISSUE THREAD

**Issue by licaon-kter** [theAkito/webmon#37]
2.0.0 F-Droid AOSP11

Should the app watch for `android.intent.action.BOOT_COMPLETED` and autostart?

**Comment by theAkito** [comment]
Is there an issue with autostart? Does it not work?

Could you please provide more information?

**Comment by theAkito** [comment]
I see now.

Do you have really long intervals set up for notification? Like, a week, for example?

Every time you open the app, the timer resets, because you open the app and already checked what websites are up or not.

So, if you have a long interval, like a week, and you open the app several times a week, you will never get a notification.



> What I don't know, what should pressing the "enable autostart" button actually do? There's no feedback, I can press it many times.

I indeed can reproduce this issue. I will check that out. 👍🏻

**Comment by licaon-kter** [comment]
15 minutes

Dunno about timer on open now, the last check date was two weeks in the past or so.

Why should I open the app, that's the point...it works...in the background...and does it thing. If I need to open the app then I'll uninstall the app and open the site to check manually :)

**Comment by theAkito** [comment]
> Why should I open the app, that's the point...it works...in the background...and does it thing. If I need to open the app then I'll uninstall the app and open the site to check manually :)

Yes. That's how I use it. I basically never open it. I just get a weekly notification. And I restart my phone at least once a week.

Nevertheless, I will investigate the no feedback issue with the "Enable Autostart" button. 👍🏻

**Comment by licaon-kter** [comment]
What does that try to do? Set an alarm? A schedjob? A wake thing?
